In [29]:
import numpy as np

In [30]:
a = np.array([1,2,3], dtype='int16') #specifying dtype is optional
print(a)

[1 2 3]


In [31]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [32]:
#Get dimension of the numpy array
b.ndim

2

In [33]:
#Get shape of the numpy array
a.shape

(3,)

In [34]:
b.shape

(2, 3)

In [35]:
#get the data type 
a.dtype

dtype('int16')

In [36]:
b.dtype

dtype('float64')

In [37]:
#get size 
a.itemsize #memory taken by item on the array in bytes

2

In [38]:
#get total size
a.size * a.itemsize

6

In [39]:
#another way to get total size
a.nbytes

6

 ### Accessing changing specific element, row, columns etc

In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [45]:
# Get a specific Element [r,c]
a[1,5]

13

In [46]:
#-ve index can be used as well
a[1,-2]

13

In [47]:
#Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [49]:
#Getting [startindex: endindex : stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [55]:
a[1,5] = 20 #replacing element
print(a)
a[:,2] = 5 #change the value of entire col.
print(a)
a[:,2] =[1,2] #changing the val to 1,2 
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [57]:
#3D example

In [59]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
#Get specific element (work outside in)
b[0,1,1]

4

In [62]:
#replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initialise Different Type of Arrays

In [63]:
#All 0s matrix 
np.zeros(5) #specify shape in parameter

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
#All 1s matrix
np.ones((4,2,2)) #can specify dtype too

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [68]:
#any other number
np.full((2,2),99) #shape , value , (optional) dtpye

array([[99, 99],
       [99, 99]])

In [69]:
np.full_like(a,4) #to take an array of such shape as 'a'

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
#Random Decimal numbers
np.random.rand(4,2) #parameter is the shape

array([[0.61312764, 0.53257728],
       [0.66646272, 0.02552539],
       [0.81197329, 0.92636834],
       [0.71935432, 0.29288572]])

In [71]:
#to get a sample based on existing shape
np.random.random_sample(a.shape)

array([[0.08566615, 0.28781108, 0.10205142, 0.50278085, 0.42542415,
        0.98238248, 0.87670134],
       [0.31813391, 0.78659361, 0.33098616, 0.97507013, 0.50704246,
        0.59243897, 0.21134087]])

In [74]:
#Random integer values
np.random.randint(3,7,size=(3,3)) #para - (optional, default = 0)startval,(optional)endval, size

array([[4, 6, 4],
       [4, 3, 6],
       [4, 4, 5]])

In [75]:
np.identity(4) #make an identity matrix of size

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
#to repeat the array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0) #para - array, no of repitition , axis (optional, default = 1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
#try to recreate the matrix without using manual input
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

In [82]:
output = np.ones((5,5))

In [83]:
zero = np.zeros((3,3))
zero[1,1] = 9
output[1:4,1:4] = zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!

In [84]:
a = np.array([1,2,3])
b = a.copy() #if not done, any changes to b, will occur at too
b[0] = 22
b

array([22,  2,  3])

### Mathematics

In [86]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [87]:
a + 3

array([4, 5, 6, 7])

In [88]:
a - 3

array([-2, -1,  0,  1])

In [89]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [90]:
a * 2

array([2, 4, 6, 8])

In [91]:
b = np.array([4,5,6,2])
a+b

array([5, 7, 9, 6])

In [92]:
a ** 2 #square

array([ 1,  4,  9, 16], dtype=int32)

In [93]:
# Take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [97]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
#to multiply these matrices
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [99]:
c = np.identity(3)
np.linalg.det(c) #to get determinant of the matrix 


1.0